### ISSUE TITLE
findOutgoingLinks doesn't work when a h-card is present

### ISSUE THREAD

**Issue by RobinBoers** [indieweb/mention-client-php#41] opened 2022-05-02 12:29 UTC
I have my posts marked up with microformats2:

```
<article class="h-entry">
    <div>
        <div>
            <p class="title">
                <i class="fa-solid fa-reply"></i> replied to 
                <a class="u-in-reply-to" href="https://micro.geheimesite.nl/post/626f9d9c0e367">https://micro.geheimesite.nl/post/626f9d9c0e367</a>
            </p>
            <div class="p-summary e-content">
                <p>The only thing I still need to do now is add support for webmention comments (which I'm testing now) and add a media endpoint for photo posts. I think the comments should be working now; this is a test :)</p>
            </div>
        </div>           

        <a class="no-underline u-url" href="https://micro.geheimesite.nl/post/626fca88eb951">
            <time class="dt-published">2022-05-02 14:11:52</time>
        </a>
    </div>            
    <div class="p-author h-card">
        <img src="/assets/me.jpeg" class="u-photo">
        <p hidden=""><a class="u-url p-name" href="https://micro.geheimesite.nl">Robijntje</a></p>
    </div>        
</article>
```

They include an h-card. Currently `findOutgoingLinks` doesn't work with this setup, because it only checks the first element in the array returned by the mf2 parser, which is the h-card. I think a possible solution is using a foreach loop and just checking all elements in the array and picking the one with type=h-entry.

I'm pretty sure my mf2 markup is fine, but if it isn't, let me know :)

**Comment by Zegnat** [comment] 2022-06-21 16:18
I think this is a duplicate of #29.

**Comment by RobinBoers** [comment] 2022-06-22 06:27
Oh wow, didn't notice that issue. Thanks anyways!

**Closed as completed** 2022-06-22 06:27 UTC
